import { Product, Category, Order, Customer, DashboardStats, RevenueData } from '@/types';

// Generate initial mock data
export const generateMockProducts = (): Product[] => [
  {
    id: '1',
    name: 'Modern Oak Dining Table',
    description: 'Elegant solid oak dining table with clean lines and natural finish. Perfect for modern dining spaces.',
    category: 'dining',
    price: 1299.99,
    discount: 10,
    stock: 15,
    images: ['/placeholder.svg'],
    materials: ['Solid Oak', 'Steel Legs'],
    dimensions: { width: 180, height: 75, depth: 90 },
    status: 'active',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    name: 'Velvet Accent Chair',
    description: 'Luxurious velvet accent chair with brass legs. Adds sophistication to any room.',
    category: 'living-room',
    price: 599.99,
    discount: 15,
    stock: 28,
    images: ['/placeholder.svg'],
    materials: ['Velvet', 'Brass', 'Hardwood Frame'],
    dimensions: { width: 75, height: 85, depth: 80 },
    status: 'active',
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: '3',
    name: 'Industrial Bookshelf',
    description: 'Five-tier industrial bookshelf with metal frame and reclaimed wood shelves.',
    category: 'storage',
    price: 449.99,
    discount: 0,
    stock: 12,
    images: ['/placeholder.svg'],
    materials: ['Reclaimed Wood', 'Iron Frame'],
    dimensions: { width: 100, height: 200, depth: 35 },
    status: 'active',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: '4',
    name: 'Upholstered King Bed',
    description: 'Luxurious king-size bed with button-tufted headboard in premium linen fabric.',
    category: 'bedroom',
    price: 1899.99,
    discount: 20,
    stock: 8,
    images: ['/placeholder.svg'],
    materials: ['Linen', 'Hardwood Frame', 'High-Density Foam'],
    dimensions: { width: 193, height: 135, depth: 215 },
    status: 'active',
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: '5',
    name: 'Marble Coffee Table',
    description: 'Contemporary coffee table featuring genuine marble top and gold-finished metal base.',
    category: 'living-room',
    price: 899.99,
    discount: 0,
    stock: 5,
    images: ['/placeholder.svg'],
    materials: ['Genuine Marble', 'Stainless Steel'],
    dimensions: { width: 120, height: 45, depth: 60 },
    status: 'active',
    createdAt: new Date('2024-02-15').toISOString(),
    updatedAt: new Date('2024-02-15').toISOString(),
  },
  {
    id: '6',
    name: 'Scandinavian Desk',
    description: 'Minimalist desk with clean lines and built-in cable management.',
    category: 'office',
    price: 749.99,
    discount: 5,
    stock: 3,
    images: ['/placeholder.svg'],
    materials: ['Ash Wood', 'Metal Legs'],
    dimensions: { width: 140, height: 75, depth: 70 },
    status: 'draft',
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-01').toISOString(),
  },
];

export const generateMockCategories = (): Category[] => [
  { id: '1', name: 'Living Room', description: 'Sofas, chairs, and coffee tables', productCount: 45, createdAt: new Date('2024-01-01').toISOString() },
  { id: '2', name: 'Bedroom', description: 'Beds, dressers, and nightstands', productCount: 38, createdAt: new Date('2024-01-01').toISOString() },
  { id: '3', name: 'Dining', description: 'Dining tables, chairs, and cabinets', productCount: 28, createdAt: new Date('2024-01-01').toISOString() },
  { id: '4', name: 'Office', description: 'Desks, chairs, and storage', productCount: 22, createdAt: new Date('2024-01-01').toISOString() },
  { id: '5', name: 'Storage', description: 'Shelves, cabinets, and organizers', productCount: 31, createdAt: new Date('2024-01-01').toISOString() },
  { id: '6', name: 'Outdoor', description: 'Patio furniture and garden sets', productCount: 19, createdAt: new Date('2024-01-01').toISOString() },
];

export const generateMockOrders = (): Order[] => [
  {
    id: '1',
    orderNumber: 'ORD-2024-001',
    customerId: '1',
    customerName: 'Sarah Johnson',
    items: [
      { productId: '1', productName: 'Modern Oak Dining Table', productImage: '/placeholder.svg', quantity: 1, price: 1299.99, total: 1299.99 },
      { productId: '2', productName: 'Velvet Accent Chair', productImage: '/placeholder.svg', quantity: 4, price: 599.99, total: 2399.96 },
    ],
    subtotal: 3699.95,
    tax: 332.99,
    shipping: 50.00,
    total: 4082.94,
    status: 'delivered',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '123 Main St',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-15').toISOString(),
  },
  {
    id: '2',
    orderNumber: 'ORD-2024-002',
    customerId: '2',
    customerName: 'Michael Chen',
    items: [
      { productId: '4', productName: 'Upholstered King Bed', productImage: '/placeholder.svg', quantity: 1, price: 1899.99, total: 1899.99 },
    ],
    subtotal: 1899.99,
    tax: 170.99,
    shipping: 75.00,
    total: 2145.98,
    status: 'shipped',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'USA',
    },
    createdAt: new Date('2024-03-10').toISOString(),
    updatedAt: new Date('2024-03-18').toISOString(),
  },
  {
    id: '3',
    orderNumber: 'ORD-2024-003',
    customerId: '3',
    customerName: 'Emily Rodriguez',
    items: [
      { productId: '3', productName: 'Industrial Bookshelf', productImage: '/placeholder.svg', quantity: 2, price: 449.99, total: 899.98 },
      { productId: '5', productName: 'Marble Coffee Table', productImage: '/placeholder.svg', quantity: 1, price: 899.99, total: 899.99 },
    ],
    subtotal: 1799.97,
    tax: 161.99,
    shipping: 60.00,
    total: 2021.96,
    status: 'processing',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '789 Pine Rd',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
    },
    createdAt: new Date('2024-03-15').toISOString(),
    updatedAt: new Date('2024-03-16').toISOString(),
  },
  {
    id: '4',
    orderNumber: 'ORD-2024-004',
    customerId: '4',
    customerName: 'David Kim',
    items: [
      { productId: '6', productName: 'Scandinavian Desk', productImage: '/placeholder.svg', quantity: 1, price: 749.99, total: 749.99 },
    ],
    subtotal: 749.99,
    tax: 67.49,
    shipping: 40.00,
    total: 857.48,
    status: 'pending',
    paymentStatus: 'paid',
    shippingAddress: {
      street: '321 Elm St',
      city: 'Austin',
      state: 'TX',
      zipCode: '73301',
      country: 'USA',
    },
    createdAt: new Date('2024-03-20').toISOString(),
    updatedAt: new Date('2024-03-20').toISOString(),
  },
];

export const generateMockCustomers = (): Customer[] => [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1 (555) 123-4567',
    address: {
      street: '123 Main St',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
    totalOrders: 3,
    totalSpent: 8250.45,
    status: 'active',
    createdAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'mchen@email.com',
    phone: '+1 (555) 234-5678',
    address: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'USA',
    },
    totalOrders: 2,
    totalSpent: 4500.22,
    status: 'active',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    phone: '+1 (555) 345-6789',
    address: {
      street: '789 Pine Rd',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
    },
    totalOrders: 5,
    totalSpent: 12750.80,
    status: 'active',
    createdAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'dkim@email.com',
    phone: '+1 (555) 456-7890',
    address: {
      street: '321 Elm St',
      city: 'Austin',
      state: 'TX',
      zipCode: '73301',
      country: 'USA',
    },
    totalOrders: 1,
    totalSpent: 857.48,
    status: 'active',
    createdAt: new Date('2024-03-05').toISOString(),
  },
];

export const generateDashboardStats = (orders: Order[], customers: Customer[]): DashboardStats => {
  const totalRevenue = orders.reduce((sum, order) => sum + order.total, 0);
  const totalOrders = orders.length;
  const totalCustomers = customers.length;
  const averageOrderValue = totalOrders > 0 ? totalRevenue / totalOrders : 0;

  return {
    totalRevenue,
    totalOrders,
    totalCustomers,
    averageOrderValue,
    revenueChange: 12.5,
    ordersChange: 8.3,
    customersChange: 15.2,
  };
};

export const generateRevenueData = (): RevenueData[] => [
  { month: 'Jan', revenue: 45000, orders: 32 },
  { month: 'Feb', revenue: 52000, orders: 38 },
  { month: 'Mar', revenue: 48000, orders: 35 },
  { month: 'Apr', revenue: 61000, orders: 42 },
  { month: 'May', revenue: 58000, orders: 40 },
  { month: 'Jun', revenue: 67000, orders: 48 },
];
